# Generated by Django 4.2.7 on 2023-11-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=100)),
                ('measurement_value', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
