# Generated by Django 4.2.7 on 2023-11-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0002_alter_datamodel_experiment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='data_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
