# Generated by Django 4.2.7 on 2023-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0008_alter_datamodel_processed_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='col_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodel',
            name='row_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
