# Generated by Django 4.2.7 on 2023-12-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0009_datamodel_col_index_datamodel_row_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='col_index',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='row_index',
        ),
    ]
