# Generated by Django 4.2.7 on 2023-12-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0010_remove_datamodel_col_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='data_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Analysis.dataname'),
        ),
    ]
