# Generated by Django 4.2.7 on 2023-12-05 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analysis', '0011_dataname_alter_datamodel_data_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='TimestampInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Analysis.dataname')),
            ],
        ),
        migrations.AddField(
            model_name='datamodel',
            name='timestamp_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data_Analysis.timestampinfo'),
            preserve_default=False,
        ),
    ]
